/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JPanel;
import util.Stock;
import util.User;

/**
 *
 * @author Passawit
 */
public class AddItem extends javax.swing.JPanel {

    private final JPanel window;
    private final User user = new User();
    private final Stock stock = new Stock();

    /**
     * Creates new form AddItem
     * @param window
     */
    public AddItem(JPanel window) {
        this.window = window;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTop = new javax.swing.JPanel();
        lbTop = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbPrice = new javax.swing.JLabel();
        tfPrice = new javax.swing.JFormattedTextField();
        lbAmount = new javax.swing.JLabel();
        tfAmount = new javax.swing.JFormattedTextField();
        lbBrand = new javax.swing.JLabel();
        tfBrand = new javax.swing.JTextField();
        lbType = new javax.swing.JLabel();
        tfType = new javax.swing.JTextField();
        bnAdd = new javax.swing.JPanel();
        lbAdd = new javax.swing.JLabel();
        bnCancel = new javax.swing.JPanel();
        lbCancel = new javax.swing.JLabel();
        errMsg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(986, 768));
        setPreferredSize(new java.awt.Dimension(986, 768));
        setSize(new java.awt.Dimension(986, 768));

        pTop.setBackground(new java.awt.Color(168, 80, 204));

        lbTop.setFont(new java.awt.Font("Paloseco", 1, 70)); // NOI18N
        lbTop.setForeground(new java.awt.Color(255, 255, 255));
        lbTop.setText("Add Product");

        javax.swing.GroupLayout pTopLayout = new javax.swing.GroupLayout(pTop);
        pTop.setLayout(pTopLayout);
        pTopLayout.setHorizontalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTopLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbTop, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        pTopLayout.setVerticalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTopLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(lbTop))
        );

        lbName.setFont(new java.awt.Font("COCOGOOSE ", 0, 24)); // NOI18N
        lbName.setText("Product name");

        tfName.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        tfName.setActionCommand("<Not Set>");
        tfName.setAlignmentX(0.0F);
        tfName.setAlignmentY(0.0F);
        tfName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfName.setMixingCutoutShape(null);

        lbPrice.setFont(new java.awt.Font("COCOGOOSE ", 0, 24)); // NOI18N
        lbPrice.setText("Price");

        tfPrice.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        lbAmount.setFont(new java.awt.Font("COCOGOOSE ", 0, 24)); // NOI18N
        lbAmount.setText("Amount");

        tfAmount.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbBrand.setFont(new java.awt.Font("COCOGOOSE ", 0, 24)); // NOI18N
        lbBrand.setText("Brand (optional)");

        tfBrand.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        tfBrand.setActionCommand("<Not Set>");
        tfBrand.setAlignmentX(0.0F);
        tfBrand.setAlignmentY(0.0F);
        tfBrand.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfBrand.setMixingCutoutShape(null);

        lbType.setFont(new java.awt.Font("COCOGOOSE ", 0, 24)); // NOI18N
        lbType.setText("Type (optional)");

        tfType.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        tfType.setActionCommand("<Not Set>");
        tfType.setAlignmentX(0.0F);
        tfType.setAlignmentY(0.0F);
        tfType.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfType.setMixingCutoutShape(null);

        bnAdd.setBackground(new java.awt.Color(229, 83, 97));
        bnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 83, 97), 3));
        bnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnAddMouseClicked(evt);
            }
        });

        lbAdd.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbAdd.setForeground(new java.awt.Color(255, 255, 255));
        lbAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAdd.setText("Add Product");

        javax.swing.GroupLayout bnAddLayout = new javax.swing.GroupLayout(bnAdd);
        bnAdd.setLayout(bnAddLayout);
        bnAddLayout.setHorizontalGroup(
            bnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bnAddLayout.setVerticalGroup(
            bnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bnAddLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bnCancel.setBackground(new java.awt.Color(255, 255, 255));
        bnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 83, 97), 3));
        bnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnCancelMouseClicked(evt);
            }
        });

        lbCancel.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbCancel.setForeground(new java.awt.Color(66, 66, 66));
        lbCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCancel.setText("Cancel");

        javax.swing.GroupLayout bnCancelLayout = new javax.swing.GroupLayout(bnCancel);
        bnCancel.setLayout(bnCancelLayout);
        bnCancelLayout.setHorizontalGroup(
            bnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnCancelLayout.createSequentialGroup()
                .addComponent(lbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bnCancelLayout.setVerticalGroup(
            bnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnCancelLayout.createSequentialGroup()
                .addComponent(lbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        errMsg.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        errMsg.setForeground(new java.awt.Color(224, 70, 84));
        errMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errMsg.setText(" ");
        errMsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbType)
                    .addComponent(lbBrand)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                        .addComponent(bnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfPrice)
                    .addComponent(tfAmount)
                    .addComponent(tfName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAmount)
                    .addComponent(lbPrice)
                    .addComponent(lbName)
                    .addComponent(errMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfBrand)
                    .addComponent(tfType))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errMsg)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnAddMouseClicked
        // TODO add your handling code here:
        String name = tfName.getText();
        String price = tfPrice.getText();
        String amount = tfAmount.getText();
        String brand = tfBrand.getText();
        String type = tfType.getText();

        if (name.equals("")) {
            errMsg.setText("name can't be empty!");
        } else if (price.equals("")) {
            errMsg.setText("price can't be empty!");
        } else if (amount.equals("")) {
            errMsg.setText("amount can't be empty!");
        } else {
            ConfirmAddItem cai = new ConfirmAddItem(name, price, amount);
            cai.setModal(true);
            cai.setVisible(true);

            if (cai.getReturnStatus()) {
                stock.addProduct(user.getProductID(), name, Double.parseDouble(price), Integer.parseInt(amount), brand, type);
                
                window.removeAll();
                window.repaint();
                window.revalidate();

                window.add(new Edit(window));
                window.repaint();
                window.revalidate();
            }
        }

    }//GEN-LAST:event_bnAddMouseClicked

    private void bnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnCancelMouseClicked
        // TODO add your handling code here:
        window.removeAll();
        window.repaint();
        window.revalidate();

        window.add(new Edit(window));
        window.repaint();
        window.revalidate();
    }//GEN-LAST:event_bnCancelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bnAdd;
    private javax.swing.JPanel bnCancel;
    private javax.swing.JLabel errMsg;
    private javax.swing.JLabel lbAdd;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbBrand;
    private javax.swing.JLabel lbCancel;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbTop;
    private javax.swing.JLabel lbType;
    private javax.swing.JPanel pTop;
    private javax.swing.JFormattedTextField tfAmount;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfName;
    private javax.swing.JFormattedTextField tfPrice;
    private javax.swing.JTextField tfType;
    // End of variables declaration//GEN-END:variables
}
