/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JPanel;
import util.User;

/**
 *
 * @author skefolksymac
 */
public class CreateStock extends javax.swing.JPanel {
    private JPanel window;
    private Quit quit = new Quit();

    /**
     * Creates new form CreateStock
     */
    public CreateStock(JPanel window) {
        initComponents();
        this.window = window;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sideBg = new javax.swing.JLabel();
        pTop = new javax.swing.JPanel();
        lbTop = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        lbCPassword = new javax.swing.JLabel();
        tfCPassword = new javax.swing.JPasswordField();
        bnQuit = new javax.swing.JPanel();
        lbQuit = new javax.swing.JLabel();
        bnContinue = new javax.swing.JPanel();
        lbContinue = new javax.swing.JLabel();
        errMsg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(1366, 768));
        bg.setMinimumSize(new java.awt.Dimension(1366, 768));
        bg.setPreferredSize(new java.awt.Dimension(1366, 768));
        bg.setSize(new java.awt.Dimension(1366, 768));

        sideBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cbg.png"))); // NOI18N
        sideBg.setAlignmentY(0.0F);

        pTop.setBackground(new java.awt.Color(168, 80, 204));

        lbTop.setFont(new java.awt.Font("Paloseco", 1, 70)); // NOI18N
        lbTop.setForeground(new java.awt.Color(255, 255, 255));
        lbTop.setText("Create new stock");

        javax.swing.GroupLayout pTopLayout = new javax.swing.GroupLayout(pTop);
        pTop.setLayout(pTopLayout);
        pTopLayout.setHorizontalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTopLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbTop, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        pTopLayout.setVerticalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTopLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(lbTop))
        );

        lbName.setFont(new java.awt.Font("COCOGOOSE ", 0, 30)); // NOI18N
        lbName.setText("Store name");

        tfName.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        tfName.setActionCommand("<Not Set>");
        tfName.setAlignmentX(0.0F);
        tfName.setAlignmentY(0.0F);
        tfName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfName.setMixingCutoutShape(null);

        lbPassword.setFont(new java.awt.Font("COCOGOOSE ", 0, 30)); // NOI18N
        lbPassword.setText("Password");

        tfPassword.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        lbCPassword.setFont(new java.awt.Font("COCOGOOSE ", 0, 30)); // NOI18N
        lbCPassword.setText("Confirm password");

        tfCPassword.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfCPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        bnQuit.setBackground(new java.awt.Color(255, 255, 255));
        bnQuit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 83, 97), 3));
        bnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnQuitMouseClicked(evt);
            }
        });

        lbQuit.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbQuit.setForeground(new java.awt.Color(66, 66, 66));
        lbQuit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuit.setText("Quit");

        javax.swing.GroupLayout bnQuitLayout = new javax.swing.GroupLayout(bnQuit);
        bnQuit.setLayout(bnQuitLayout);
        bnQuitLayout.setHorizontalGroup(
            bnQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnQuitLayout.createSequentialGroup()
                .addComponent(lbQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bnQuitLayout.setVerticalGroup(
            bnQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnQuitLayout.createSequentialGroup()
                .addComponent(lbQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bnContinue.setBackground(new java.awt.Color(229, 83, 97));
        bnContinue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 83, 97), 3));
        bnContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnContinueMouseClicked(evt);
            }
        });

        lbContinue.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbContinue.setForeground(new java.awt.Color(255, 255, 255));
        lbContinue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbContinue.setText("Continue");

        javax.swing.GroupLayout bnContinueLayout = new javax.swing.GroupLayout(bnContinue);
        bnContinue.setLayout(bnContinueLayout);
        bnContinueLayout.setHorizontalGroup(
            bnContinueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bnContinueLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bnContinueLayout.setVerticalGroup(
            bnContinueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bnContinueLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        errMsg.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        errMsg.setForeground(new java.awt.Color(224, 70, 84));
        errMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errMsg.setText(" ");
        errMsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sideBg)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(bnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(330, 330, 330)
                        .addComponent(bnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfName)
                                .addComponent(errMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBg)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(errMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void custom() {
        quit.init();
    }
    
    private void bnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnQuitMouseClicked
        // TODO add your handling code here:
        quit.setModal(true);
        quit.setVisible(true);
        
        if (quit.getReturnStatus()) {
            System.exit(0);
        } else {
            quit.setVisible(false);
        }
    }//GEN-LAST:event_bnQuitMouseClicked

    private void bnContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnContinueMouseClicked
        // TODO add your handling code here:
        String name = tfName.getText();
        String password = String.valueOf(tfPassword.getPassword());
        String cPassword = String.valueOf(tfCPassword.getPassword());
        
        if (name.equals("")) {
            errMsg.setText("name can't be empty!");
        } else if (password.equals("")) {
            errMsg.setText("password can't be empty!");
        } else if (!password.equals(cPassword)) {
            errMsg.setText("password doesn't match!");
        } else {
            user.insertUser(name, password, 1, 1);
            
            window.removeAll();
            window.repaint();
            window.revalidate();

            window.add(new Welcome(window));
            window.repaint();
            window.revalidate();
        }
    }//GEN-LAST:event_bnContinueMouseClicked

    private final User user = new User();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bnContinue;
    private javax.swing.JPanel bnQuit;
    private javax.swing.JLabel errMsg;
    private javax.swing.JLabel lbCPassword;
    private javax.swing.JLabel lbContinue;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbQuit;
    private javax.swing.JLabel lbTop;
    private javax.swing.JPanel pTop;
    private javax.swing.JLabel sideBg;
    private javax.swing.JPasswordField tfCPassword;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
