/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JPanel;
import util.Product;
import util.Stock;

/**
 *
 * @author Passawit
 */
public class EditItem extends javax.swing.JPanel {
    private JPanel window;
    private final Stock stock = new Stock();
    private String productID;
    private Product thisProduct;

    /**
     * Creates new form EditItem
     */
    public EditItem(JPanel window, String productID) {
        this.window = window;
        this.productID = productID;
        thisProduct = stock.getProduct(productID);
        
        initComponents();
        custom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTop = new javax.swing.JPanel();
        lbTop = new javax.swing.JLabel();
        lbProductID = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbPrice = new javax.swing.JLabel();
        tfPrice = new javax.swing.JFormattedTextField();
        lbAmount = new javax.swing.JLabel();
        tfAmount = new javax.swing.JFormattedTextField();
        bnEdit = new javax.swing.JPanel();
        lbEdit = new javax.swing.JLabel();
        bnCancel = new javax.swing.JPanel();
        lbCancel = new javax.swing.JLabel();
        bnDelete = new javax.swing.JPanel();
        lbDelete = new javax.swing.JLabel();
        errMsg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(986, 768));
        setLayout(null);

        pTop.setBackground(new java.awt.Color(168, 80, 204));

        lbTop.setFont(new java.awt.Font("Paloseco", 1, 70)); // NOI18N
        lbTop.setForeground(new java.awt.Color(255, 255, 255));
        lbTop.setText("Edit Product");

        lbProductID.setFont(new java.awt.Font("PT Mono", 0, 72)); // NOI18N
        lbProductID.setForeground(new java.awt.Color(255, 255, 255));
        lbProductID.setText("#00000");

        javax.swing.GroupLayout pTopLayout = new javax.swing.GroupLayout(pTop);
        pTop.setLayout(pTopLayout);
        pTopLayout.setHorizontalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTopLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbTop, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbProductID)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        pTopLayout.setVerticalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTopLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTop)
                    .addComponent(lbProductID)))
        );

        add(pTop);
        pTop.setBounds(0, 40, 986, 110);

        lbName.setFont(new java.awt.Font("COCOGOOSE ", 0, 30)); // NOI18N
        lbName.setText("Product name");
        add(lbName);
        lbName.setBounds(56, 204, 236, 40);

        tfName.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        tfName.setActionCommand("<Not Set>");
        tfName.setAlignmentX(0.0F);
        tfName.setAlignmentY(0.0F);
        tfName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfName.setMixingCutoutShape(null);
        add(tfName);
        tfName.setBounds(56, 250, 869, 50);

        lbPrice.setFont(new java.awt.Font("COCOGOOSE ", 0, 30)); // NOI18N
        lbPrice.setText("Price");
        add(lbPrice);
        lbPrice.setBounds(56, 334, 84, 40);

        tfPrice.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        add(tfPrice);
        tfPrice.setBounds(56, 380, 869, 50);

        lbAmount.setFont(new java.awt.Font("COCOGOOSE ", 0, 30)); // NOI18N
        lbAmount.setText("Amount");
        add(lbAmount);
        lbAmount.setBounds(56, 464, 124, 40);

        tfAmount.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        add(tfAmount);
        tfAmount.setBounds(56, 510, 869, 50);

        bnEdit.setBackground(new java.awt.Color(168, 80, 204));
        bnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 80, 204), 3));
        bnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnEditMouseClicked(evt);
            }
        });

        lbEdit.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbEdit.setForeground(new java.awt.Color(255, 255, 255));
        lbEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEdit.setText("Edit Product");

        javax.swing.GroupLayout bnEditLayout = new javax.swing.GroupLayout(bnEdit);
        bnEdit.setLayout(bnEditLayout);
        bnEditLayout.setHorizontalGroup(
            bnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bnEditLayout.setVerticalGroup(
            bnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(bnEdit);
        bnEdit.setBounds(390, 620, 170, 60);

        bnCancel.setBackground(new java.awt.Color(255, 255, 255));
        bnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 83, 97), 3));
        bnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnCancelMouseClicked(evt);
            }
        });

        lbCancel.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbCancel.setForeground(new java.awt.Color(66, 66, 66));
        lbCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCancel.setText("Cancel");

        javax.swing.GroupLayout bnCancelLayout = new javax.swing.GroupLayout(bnCancel);
        bnCancel.setLayout(bnCancelLayout);
        bnCancelLayout.setHorizontalGroup(
            bnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnCancelLayout.createSequentialGroup()
                .addComponent(lbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bnCancelLayout.setVerticalGroup(
            bnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnCancelLayout.createSequentialGroup()
                .addComponent(lbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(bnCancel);
        bnCancel.setBounds(60, 620, 170, 60);

        bnDelete.setBackground(new java.awt.Color(229, 83, 97));
        bnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 83, 97), 3));
        bnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnDeleteMouseClicked(evt);
            }
        });

        lbDelete.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbDelete.setForeground(new java.awt.Color(255, 255, 255));
        lbDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDelete.setText("Delete");

        javax.swing.GroupLayout bnDeleteLayout = new javax.swing.GroupLayout(bnDelete);
        bnDelete.setLayout(bnDeleteLayout);
        bnDeleteLayout.setHorizontalGroup(
            bnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bnDeleteLayout.setVerticalGroup(
            bnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(bnDelete);
        bnDelete.setBounds(750, 620, 170, 60);

        errMsg.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        errMsg.setForeground(new java.awt.Color(224, 70, 84));
        errMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errMsg.setText(" ");
        errMsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(errMsg);
        errMsg.setBounds(56, 177, 869, 21);
    }// </editor-fold>//GEN-END:initComponents

    private void custom() {
        lbProductID.setText("#" + thisProduct.getProductID());
        tfName.setText(thisProduct.getProductName());
        tfPrice.setText(thisProduct.getProductPrice()+"");
        tfAmount.setText(thisProduct.getProductAmount()+"");
    }
    
    private void bnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnEditMouseClicked
        // TODO add your handling code here:
        String name = tfName.getText();
        String price = tfPrice.getText();
        String amount = tfAmount.getText();

        if (name.equals("")) {
            errMsg.setText("name can't be empty!");
        } else if (price.equals("")) {
            errMsg.setText("price can't be empty!");
        } else if (amount.equals("")) {
            errMsg.setText("amount can't be empty!");
        } else {
            ConfirmEditItem cai = new ConfirmEditItem(name, price, amount);
            cai.setModal(true);
            cai.setVisible(true);

            if (cai.getReturnStatus()) {
                stock.editProduct(productID, name, Double.parseDouble(price), Integer.parseInt(amount));

                window.removeAll();
                window.repaint();
                window.revalidate();

                window.add(new Edit(window));
                window.repaint();
                window.revalidate();
            }
        }
    }//GEN-LAST:event_bnEditMouseClicked

    private void bnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnCancelMouseClicked
        // TODO add your handling code here:
        window.removeAll();
        window.repaint();
        window.revalidate();

        window.add(new Edit(window));
        window.repaint();
        window.revalidate();
    }//GEN-LAST:event_bnCancelMouseClicked

    private void bnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnDeleteMouseClicked
        // TODO add your handling code here:
        String name = tfName.getText();
        String price = tfPrice.getText();
        String amount = tfAmount.getText();
        ConfirmDeleteItem cai = new ConfirmDeleteItem(name, price, amount);
            cai.setModal(true);
            cai.setVisible(true);

            if (cai.getReturnStatus()) {
                stock.deleteProduct(productID);

                window.removeAll();
                window.repaint();
                window.revalidate();

                window.add(new Edit(window));
                window.repaint();
                window.revalidate();
            }
        
    }//GEN-LAST:event_bnDeleteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bnCancel;
    private javax.swing.JPanel bnDelete;
    private javax.swing.JPanel bnEdit;
    private javax.swing.JLabel errMsg;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbCancel;
    private javax.swing.JLabel lbDelete;
    private javax.swing.JLabel lbEdit;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbProductID;
    private javax.swing.JLabel lbTop;
    private javax.swing.JPanel pTop;
    private javax.swing.JFormattedTextField tfAmount;
    private javax.swing.JTextField tfName;
    private javax.swing.JFormattedTextField tfPrice;
    // End of variables declaration//GEN-END:variables
}
