/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.mongodb.DBCollection;
import javax.swing.JPanel;
import util.Database;
import util.User;

/**
 *
 * @author Passawit
 */
public class Setting extends javax.swing.JPanel {
    private JPanel window;
    private User user = new User();
    private Security security = new Security();
    private Delete delete = new Delete();
    private Saved saved = new Saved();

    /**
     * Creates new form Setting
     */
    public Setting(JPanel window) {
        this.window = window;
        initComponents();
        custom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbOld = new javax.swing.JLabel();
        tfOld = new javax.swing.JPasswordField();
        lbPassword = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        lbCPassword = new javax.swing.JLabel();
        tfCPassword = new javax.swing.JPasswordField();
        bnSave = new javax.swing.JPanel();
        lbSave = new javax.swing.JLabel();
        errMsg = new javax.swing.JLabel();
        bnDelete = new javax.swing.JPanel();
        lbDelete = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(986, 768));
        setSize(new java.awt.Dimension(986, 768));

        lbName.setFont(new java.awt.Font("COCOGOOSE ", 0, 30)); // NOI18N
        lbName.setText("Store name");

        tfName.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        tfName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        lbOld.setFont(new java.awt.Font("COCOGOOSE ", 0, 30)); // NOI18N
        lbOld.setText("Old password");

        tfOld.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfOld.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        lbPassword.setFont(new java.awt.Font("COCOGOOSE ", 0, 30)); // NOI18N
        lbPassword.setText("New password");

        tfPassword.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        lbCPassword.setFont(new java.awt.Font("COCOGOOSE ", 0, 30)); // NOI18N
        lbCPassword.setText("Confirm password");

        tfCPassword.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfCPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 189, 189), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        bnSave.setBackground(new java.awt.Color(255, 255, 255));
        bnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 83, 97), 3));
        bnSave.setMaximumSize(new java.awt.Dimension(170, 60));
        bnSave.setPreferredSize(new java.awt.Dimension(170, 60));
        bnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnSaveMouseClicked(evt);
            }
        });

        lbSave.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbSave.setForeground(new java.awt.Color(66, 66, 66));
        lbSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSave.setText("Save");
        lbSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbSave.setMaximumSize(new java.awt.Dimension(170, 60));
        lbSave.setMinimumSize(new java.awt.Dimension(170, 60));
        lbSave.setMixingCutoutShape(null);
        lbSave.setPreferredSize(new java.awt.Dimension(170, 60));

        javax.swing.GroupLayout bnSaveLayout = new javax.swing.GroupLayout(bnSave);
        bnSave.setLayout(bnSaveLayout);
        bnSaveLayout.setHorizontalGroup(
            bnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 158, Short.MAX_VALUE)
        );
        bnSaveLayout.setVerticalGroup(
            bnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
        );

        errMsg.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        errMsg.setForeground(new java.awt.Color(224, 70, 84));
        errMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errMsg.setText(" ");
        errMsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bnDelete.setBackground(new java.awt.Color(229, 83, 97));
        bnDelete.setMaximumSize(new java.awt.Dimension(170, 60));
        bnDelete.setPreferredSize(new java.awt.Dimension(170, 60));
        bnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnDeleteMouseClicked(evt);
            }
        });

        lbDelete.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbDelete.setForeground(new java.awt.Color(255, 255, 255));
        lbDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDelete.setText("Delete");
        lbDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDelete.setMaximumSize(new java.awt.Dimension(170, 60));
        lbDelete.setMinimumSize(new java.awt.Dimension(170, 60));
        lbDelete.setMixingCutoutShape(null);
        lbDelete.setPreferredSize(new java.awt.Dimension(170, 60));
        lbDelete.setSize(new java.awt.Dimension(170, 60));

        javax.swing.GroupLayout bnDeleteLayout = new javax.swing.GroupLayout(bnDelete);
        bnDelete.setLayout(bnDeleteLayout);
        bnDeleteLayout.setHorizontalGroup(
            bnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bnDeleteLayout.setVerticalGroup(
            bnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbOld, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOld, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(386, 386, 386)
                        .addComponent(bnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(errMsg)
                .addGap(19, 19, 19)
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbOld, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfOld, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnSaveMouseClicked
        // TODO add your handling code here:
        String name = tfName.getText();
        String old = String.valueOf(tfOld.getPassword());
        String password = String.valueOf(tfPassword.getPassword());
        String cPassword = String.valueOf(tfCPassword.getPassword());

        if (user.getPassword().equals(old)) {
            if (name.equals("")) {
                errMsg.setText("name can't be empty!");
            } else if (password.equals("")) {
                errMsg.setText("password can't be empty!");
            } else if (!password.equals(cPassword)) {
                errMsg.setText("password doesn't match!");
            } else {
                user.updateUser(name, password, user.getProductCount(), user.getTransactionCount());
                tfName.setText(user.getName());
                tfOld.setText("");
                tfPassword.setText("");
                tfCPassword.setText("");
                errMsg.setText(" ");
                
                saved.setModal(true);
                saved.setVisible(true);
            }
        } else {
            errMsg.setText("invalid old password!");
        }
    }//GEN-LAST:event_bnSaveMouseClicked

    private void bnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnDeleteMouseClicked
        // TODO add your handling code here:
        security.setModal(true);
        security.setVisible(true);
        
        if (security.getReturnStatus()) {
            delete.setModal(true);
            delete.setVisible(true);
            
            if (delete.getReturnStatus()) {
                Database d = new Database();
                DBCollection user = d.getCollection("user");
                DBCollection stock = d.getCollection("stock");
                DBCollection transactions = d.getCollection("transactions");
                user.drop();
                stock.drop();
                transactions.drop();

                window.removeAll();
                window.repaint();
                window.revalidate();

                window.add(new CreateStock(window));
                window.repaint();
                window.revalidate();
            }
        }
    }//GEN-LAST:event_bnDeleteMouseClicked

    private void custom() {
        tfName.setText(user.getName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bnDelete;
    private javax.swing.JPanel bnSave;
    private javax.swing.JLabel errMsg;
    private javax.swing.JLabel lbCPassword;
    private javax.swing.JLabel lbDelete;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbOld;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbSave;
    private javax.swing.JPasswordField tfCPassword;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfOld;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
