/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import util.Loading;
import util.User;

/**
 *
 * @author Passawit
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        custom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        window = new javax.swing.JPanel();
        loadingPn = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();
        lbStock = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        window.setBackground(new java.awt.Color(255, 255, 255));
        window.setPreferredSize(new java.awt.Dimension(1366, 768));
        window.setSize(new java.awt.Dimension(1366, 768));

        loadingPn.setBackground(new java.awt.Color(255, 255, 255));
        loadingPn.setPreferredSize(new java.awt.Dimension(1366, 768));
        loadingPn.setRequestFocusEnabled(false);
        loadingPn.setSize(new java.awt.Dimension(1366, 768));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N

        lbStock.setFont(new java.awt.Font("Cocogoose", 0, 130)); // NOI18N
        lbStock.setForeground(new java.awt.Color(66, 66, 66));
        lbStock.setText(" jStock");

        loading.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        loading.setForeground(new java.awt.Color(66, 66, 66));
        loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loading.setText("Loading ");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout loadingPnLayout = new javax.swing.GroupLayout(loadingPn);
        loadingPn.setLayout(loadingPnLayout);
        loadingPnLayout.setHorizontalGroup(
            loadingPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingPnLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(logo)
                .addGroup(loadingPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loadingPnLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbStock)
                        .addGap(40, 40, 40)
                        .addComponent(bg))
                    .addGroup(loadingPnLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        loadingPnLayout.setVerticalGroup(
            loadingPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingPnLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(logo))
            .addComponent(bg)
            .addGroup(loadingPnLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(lbStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loading))
        );

        javax.swing.GroupLayout windowLayout = new javax.swing.GroupLayout(window);
        window.setLayout(windowLayout);
        windowLayout.setHorizontalGroup(
            windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowLayout.createSequentialGroup()
                .addComponent(loadingPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        windowLayout.setVerticalGroup(
            windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowLayout.createSequentialGroup()
                .addComponent(loadingPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void custom() {
        JPanel panel = null;
        if (user.haveUser()) {
            panel = new SidePanel(window);
        } else {
            panel = new CreateStock(window);
        }
        new Loading(loading, 3, window, panel).start();
    }
    
    public void init() {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainGUI().setVisible(true);
        });
    }

    private final User user = new User();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel lbStock;
    private javax.swing.JLabel loading;
    private javax.swing.JPanel loadingPn;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel window;
    // End of variables declaration//GEN-END:variables
}
