/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JPanel;

/**
 *
 * @author Passawit
 */
public class Welcome extends javax.swing.JPanel {
    JPanel window;
    

    /**
     * Creates new form Welcome
     */
    public Welcome(JPanel window) {
        this.window = window;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bnContinue = new javax.swing.JPanel();
        lbContinue = new javax.swing.JLabel();
        lbWelcome = new javax.swing.JLabel();
        lbTo = new javax.swing.JLabel();
        lbStock = new javax.swing.JLabel();
        lbLorem = new javax.swing.JLabel();
        card = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setSize(new java.awt.Dimension(1366, 768));

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setMaximumSize(new java.awt.Dimension(1366, 768));
        bg.setPreferredSize(new java.awt.Dimension(1366, 768));
        bg.setSize(new java.awt.Dimension(1366, 768));
        bg.setLayout(null);

        bnContinue.setBackground(new java.awt.Color(229, 83, 97));
        bnContinue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 83, 97), 3));
        bnContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnContinueMouseClicked(evt);
            }
        });

        lbContinue.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbContinue.setForeground(new java.awt.Color(255, 255, 255));
        lbContinue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbContinue.setText("Continue");

        javax.swing.GroupLayout bnContinueLayout = new javax.swing.GroupLayout(bnContinue);
        bnContinue.setLayout(bnContinueLayout);
        bnContinueLayout.setHorizontalGroup(
            bnContinueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bnContinueLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bnContinueLayout.setVerticalGroup(
            bnContinueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnContinueLayout.createSequentialGroup()
                .addComponent(lbContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(bnContinue);
        bnContinue.setBounds(600, 560, 170, 60);

        lbWelcome.setFont(new java.awt.Font("Futura", 0, 110)); // NOI18N
        lbWelcome.setForeground(new java.awt.Color(224, 70, 84));
        lbWelcome.setText("WELCOME");
        bg.add(lbWelcome);
        lbWelcome.setBounds(400, 190, 580, 147);

        lbTo.setFont(new java.awt.Font("Paloseco", 0, 90)); // NOI18N
        lbTo.setForeground(new java.awt.Color(224, 70, 84));
        lbTo.setText("to");
        bg.add(lbTo);
        lbTo.setBounds(410, 380, 90, 109);

        lbStock.setFont(new java.awt.Font("Cocogoose", 0, 130)); // NOI18N
        lbStock.setForeground(new java.awt.Color(151, 72, 183));
        lbStock.setText(" jStock");
        bg.add(lbStock);
        lbStock.setBounds(480, 320, 500, 187);

        lbLorem.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        lbLorem.setForeground(new java.awt.Color(66, 66, 66));
        lbLorem.setText("easiest way to manage your stock");
        lbLorem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bg.add(lbLorem);
        lbLorem.setBounds(530, 500, 320, 21);

        card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card.gif"))); // NOI18N
        bg.add(card);
        card.setBounds(0, 0, 1366, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bnContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnContinueMouseClicked
        // TODO add your handling code here:
        window.removeAll();
        window.repaint();
        window.revalidate();

        window.add(new SidePanel(window));
        window.repaint();
        window.revalidate();
        
    }//GEN-LAST:event_bnContinueMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bnContinue;
    private javax.swing.JLabel card;
    private javax.swing.JLabel lbContinue;
    private javax.swing.JLabel lbLorem;
    private javax.swing.JLabel lbStock;
    private javax.swing.JLabel lbTo;
    private javax.swing.JLabel lbWelcome;
    // End of variables declaration//GEN-END:variables
}
